config/routes.rb
Rails.application.routes.draw do
  resources :listings
  get 'home/index'
  devise_for :users, controllers:{ omniauth_callbacks: "users/omniauth_callbacks" }	
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user


	self.per_page = 6

	# attr_accessor :cover

	# after_save :save_cover_image, if: :cover

	# def save_cover_image
	# 	filename = cover.original_filename

	# 	folder = "public/images/#{id}/cover"

	# 	FileUtils::mkdir_p folder

	# 	f =File.open File.join(folder, filename), "wb"

	# 	f.write cover.read()
	# 	f.close

	# 	self.cover = nil
	# 	update cover_filename: filename

	# end

	 mount_uploader :cover, CoverUploader

	# mount_uploader :photo, ImageUploader

	# before_save :update_photo_attributes

	# private

	# def update_photo_attributes
	# 	if photo.present? && photo_ahnged?
	# 		self.photo_content_type = photo.file.content_type
	# 		self.photo_file_size = photo.file.size
	# 	end
	# end

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

   validates:username, presence: true
   validates:city, presence: true
   validates:state, presence: true
   validates:zip, presence: true
   validates:phone_number, presence: true

has_many :listings

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.provider = auth.provider
    user.uid = auth.uid
    user.password = Devise.friendly_token[0,20]
  end
  end
  def has_facebook_linked?
  self.provider.present? && self.uid.present?
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :current_password, :organization_name, :organization_adress, :organization_adress2, :city, :state, :zip, :donor, :phone_number])
	 	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:update, :edit, :destroy]

  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
    # redirect_to root_path
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
  end

  # GET /listings/new
  def new

    @listing = current_user.listings.build
    @user = current_user 
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.build(listing_params)
    @user =current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to root_path, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to root_path, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      if(user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :adress, :cover, :_destroy)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController

	Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController

	Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  	
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	 @listings = Listing.all.order("created_at DESC").paginate(:page => params[:page])
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <div class="alert alert-primary" role="alert">
      <h3>#{sentence}</h3>
    </div>
     <div class="alert alert-danger" role="alert">
       #{messages}
    </div>
      
     
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="alert alert-primary" role="alert">
      <p class="notice"><%= notice %> </p>
    </div>
    <% end %>
     <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <p class="alert"><%= alert %> </p>
    </div>
    <% end %>
<%if user_signed_in? %>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to   image_tag ("loginlogo"), size:7*8 %></h5>
      <nav class="my-2 my-md-0 mr-md-3 sticky-top">
        <%= link_to 'Show Listing',listings_path,class:'p-2 text-dark' %>
        <%= link_to 'Create Listing',new_listing_path,class:'p-2 text-dark' %>
         <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:'btn btn-outline-warning' %>
      </nav>
      
      <% else %> 
      <% end %>
</div>
  <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for @listing do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>



<!-- <%= form_with(model: @listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
 -->

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
  <% if current_user && current_user == listing.user %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= link_to 'Show', listing %></td>
        
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= form_with(model: @listing, local: true) do |form| %>

<div class="form-row justify-content-md-center">
    <div class="form-group col-md-4">
      <%= form.text_field :name, autofocus: true, class:'radiusfull',placeholder: 'Enter Your Furniture Name' %>
    </div>
</div>
<div class="form-row justify-content-md-center">
    <div class="form-group col-md-4">
      <%= form.text_field :description, autofocus: true, class:'radiusfull',placeholder: 'Description' %>
    </div>
</div>
<div class="form-row justify-content-md-center">
    <div class="form-group col-md-4">
      <%= form.text_field :adress, autofocus: true, class:'radiusfull',placeholder: 'Phone Number' %>
    </div>
</div>
<div class="form-row justify-content-md-center">
    <div class="form-group col-md-4">
      <%= form.file_field :cover %>
    </div>
</div>
<div class="form-row justify-content-md-center">
    <div class="form-group col-md-4">
      <%= form.submit class:'btn btn-outline-primary' %>
    </div>
</div>
<div class="form-row justify-content-md-center">
    <div class="form-group col-md-4">
      <%= link_to 'Back', listings_path %>
    </div>
</div>

<% end %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<!-- <% if current_user && current_user == @listing.user %> -->
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<!-- <% end %> -->
<%= link_to 'Back', listings_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/_dashboard.html.erb
<% @listings.each_slice(3) do |listings| %>
<div class="container ">
    <div class="row">
        <% listings.each do |listing| %>
            <div class="col-sm-4">
                    <div class="card text-center " style="width: 18rem; height: 25rem;">
                          <div class="card-img-wrap">
                        <%= image_tag listing.cover.url :class=>"card-body" if listing.cover?  %>
                        <div class="card-body">
                            <h6 class="card-title"><%= listing.name %></h6>
                            <p><%= listing.description %><p>
                         	<%= link_to 'View Details', listing, class:'details' %> 
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <br>
</div>
<% end %>
<%= will_paginate @listings,  renderer: WillPaginate::ActionView::BootstrapLinkRenderer,list_classes: %w(pagination justify-content-center) %>

app/views/welcome/_home.html.erb
<body class="background">
  <div class="container">
        <div class="row text-center">
          <div class="col-sm-12">
            <%= image_tag ("loginlogo")%>
          </div>
        </div>
        <br><br><br><br>
        <div class="row text-center">
            <div class="col-sm-12 ">
              <%=link_to 'SIGN UP', new_user_registration_path, class:"signup"%>
          </div>
          </div>
          <br><br>
          <div class="row text-center">
            <div class="col-sm-12 ">
                <%=link_to 'SIGN IN', new_user_session_path, class:"signup"%>
          </div>
        </div>
      </div>

app/views/welcome/index.html.erb
<%if user_signed_in? %>
    <%= render 'dashboard' %>
  <% else %>
    <%= render 'home' %>
<% end %>